# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots_app', '0002_auto_20190924_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
