# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots_app', '0010_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_images/'),
        ),
    ]
