# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-12 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Author notes'),
        ),
    ]
