# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-16 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20190916_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.DateField(),
        ),
    ]
